import type { BunRequest } from "bun";
import { AccountingError, budgetUsageDashboard, deleteBudget, deletePricingGroup, getBudgetAdminDetail, pricingAdminDetail, saveBudget, saveBudgetSettings, saveBudgetWindow, saveCodexBudgetAnchor, savePricingGroup, savePricingVersion, setUnlimited, usageDashboard } from "./accounting";
import { RequestScopeError, requireWorkspaceRequestScope, runWithWorkspaceScope } from "./request-scope";
import { admitWorkspaceWrite } from "./workspaces";
import { searchModelsDev } from "./models-dev";

const MAX_BODY = 32 * 1024;
function response(body: unknown, status = 200) { return Response.json(body, { status, headers: { "cache-control": "no-store" } }); }
function fail(error: unknown) { if (error instanceof AccountingError || error instanceof RequestScopeError) return response({ error: error.message, ...(error instanceof AccountingError && error.code ? { code: error.code } : {}) }, error.status); console.error("Accounting request failed."); return response({ error: "Accounting is temporarily unavailable." }, 503); }
async function body(request: BunRequest): Promise<Record<string, unknown>> { if (request.headers.get("content-type")?.split(";", 1)[0].toLowerCase() !== "application/json") throw new AccountingError("Content-Type must be application/json.", 415); const length = Number(request.headers.get("content-length") ?? 0); if (!Number.isSafeInteger(length) || length > MAX_BODY) throw new AccountingError("Request body is invalid or too large."); const bytes = new Uint8Array(await request.arrayBuffer()); if (bytes.byteLength > MAX_BODY) throw new AccountingError("Request body is invalid or too large."); try { const parsed: unknown = JSON.parse(new TextDecoder().decode(bytes)); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); return parsed as Record<string, unknown>; } catch { throw new AccountingError("Request body must be valid JSON."); } }
async function scoped<T>(request: BunRequest, mutate: boolean, operation: (workspaceId: string) => Promise<T>): Promise<Response> { try { const scope = await requireWorkspaceRequestScope(request, { mutate }); const admission = mutate ? await admitWorkspaceWrite(scope.workspace.id) : undefined; if (mutate && !admission) throw new AccountingError("Workspace is unavailable.", 409); try { return response(await runWithWorkspaceScope(scope, () => operation(scope.workspace.id))); } finally { admission?.release(); } } catch (error) { return fail(error); } }
function idAfter(request: BunRequest, prefix: string): string { const path = new URL(request.url).pathname; const value = path.slice(prefix.length); if (!value || value.includes("/")) throw new AccountingError("Resource not found.", 404); return decodeURIComponent(value); }

export function getPricing(request: BunRequest) { return scoped(request, false, pricingAdminDetail); }
export async function getPricingModels(request: BunRequest) { try { const scope = await requireWorkspaceRequestScope(request); const url = new URL(request.url); return response({ models: await runWithWorkspaceScope(scope, () => searchModelsDev(url.searchParams.get("q") ?? "", Number(url.searchParams.get("limit") ?? 50))) }); } catch (error) { return fail(error); } }
export async function postPricingGroup(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => ({ id: await savePricingGroup(workspaceId, { name: value.name, modelIds: value.modelIds, canonical: value.canonical }) })); }
export async function patchPricingGroup(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => ({ id: await savePricingGroup(workspaceId, { id: idAfter(request, "/api/model-pricing/groups/"), name: value.name, modelIds: value.modelIds, canonical: value.canonical }) })); }
export function deletePricingGroupHttp(request: BunRequest) { return scoped(request, true, async (workspaceId) => { await deletePricingGroup(workspaceId, idAfter(request, "/api/model-pricing/groups/")); return { ok: true }; }); }
export async function postPricingVersion(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, (workspaceId) => savePricingVersion(workspaceId, { groupId: value.groupId, rates: value.rates, tiers: value.tiers, mode: value.mode })); }

export function getBudgets(request: BunRequest) { return scoped(request, false, getBudgetAdminDetail); }
export async function postBudget(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => { await saveBudget(workspaceId, { keyId: value.keyId, limitMicros: value.limitMicros, enabled: value.enabled }); return { ok: true }; }); }
export function deleteBudgetHttp(request: BunRequest) { return scoped(request, true, async (workspaceId) => { await deleteBudget(workspaceId, idAfter(request, "/api/budgets/")); return { ok: true }; }); }
export async function patchBudgetWindow(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => { await saveBudgetWindow(workspaceId, { startAt: value.startAt, endAt: value.endAt }); return { ok: true }; }); }
export async function patchBudgetCodexAnchor(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => { await saveCodexBudgetAnchor(workspaceId, value.accountId); return { ok: true }; }); }
export async function patchBudgetUnlimited(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => { if (typeof value.active !== "boolean") throw new AccountingError("Unlimited state is required."); await setUnlimited(workspaceId, value.active, value.autoEnd === true); return { ok: true }; }); }
export async function patchBudgetSettings(request: BunRequest) { let value: Record<string, unknown>; try { value = await body(request); } catch (error) { return fail(error); } return scoped(request, true, async (workspaceId) => { await saveBudgetSettings(workspaceId, { exclusions: value.exclusions, beyondEnabled: value.beyondEnabled, beyondModels: value.beyondModels }); return { ok: true }; }); }
export function getUsage(request: BunRequest) { const url = new URL(request.url); return scoped(request, false, (workspaceId) => url.searchParams.get("preset") === "budget" ? budgetUsageDashboard(workspaceId, url.searchParams.get("granularity") ?? undefined) : usageDashboard(workspaceId, { preset: url.searchParams.get("preset") ?? undefined, from: url.searchParams.get("from"), to: url.searchParams.get("to"), granularity: url.searchParams.get("granularity") ?? undefined })); }
