import { expect, test } from "bun:test";

Bun.env.NODE_ENV = "development"; Bun.env.APP_ORIGIN = ""; Bun.env.AUTH_DEFAULT_PASSWORD = "accounting-job-shutdown"; Bun.env.DATABASE_URL = `file:/tmp/opencode/rawroute-accounting-job-${crypto.randomUUID()}.db`; Bun.env.RAWROUTE_DATA_DIR = `/tmp/opencode/rawroute-accounting-job-${crypto.randomUUID()}`;
const accounting = await import("./accounting"); const { db } = await import("./db"); const workspaces = await import("./workspaces"); const providers = await import("./providers"); const keys = await import("./gateway-keys");
const rates = (amount = 1) => ({ inputMicrosPerMillion: amount * 1_000_000, outputMicrosPerMillion: amount * 1_000_000, cacheReadMicrosPerMillion: 0, cacheCreationMicrosPerMillion: 0 });

test("shutdown waits for a claimed pricing invocation", async () => {
  await workspaces.ensureWorkspaceSchema(); await providers.ensureProviderSchema(); await keys.ensureGatewayKeySchema(); await accounting.ensureAccountingSchema();
  const workspace = await workspaces.createWorkspace(`Job ${crypto.randomUUID()}`); const key = await keys.createGatewayKey(workspace.id, "job", crypto.randomUUID()); const provider = await providers.createProvider(workspace.id, { name: "Job", prefix: `job-${crypto.randomUUID().replaceAll("-", "").slice(0, 16)}`, baseUrl: "https://example.invalid", protocol: "openai-responses", authType: "none" }); const model = await providers.createProviderModel(workspace.id, provider.id, { name: "Job", gatewaySuffix: "gpt-job", upstreamModel: "gpt-job" }); const group = await accounting.savePricingGroup(workspace.id, { name: "Job", modelIds: [model.id] }); await accounting.savePricingVersion(workspace.id, { groupId: group, rates: rates() }); await accounting.saveBudget(workspace.id, { keyId: key.key.id, limitMicros: 1_000 });
  const hooks = accounting.gatewayAccountingHooks(); const attempt = { attemptId: crypto.randomUUID(), requestId: crypto.randomUUID(), workspaceId: workspace.id, gatewayKeyId: key.key.id, requestedModel: model.gatewayModelId, model: { id: model.gatewayModelId, providerId: provider.id, providerPrefix: "job", name: "Job", upstreamModel: "gpt-job", protocol: "openai-responses", source: "custom" }, providerId: provider.id, protocol: "openai-responses", startedAt: Date.now(), requestBodyBytes: 1, payload: { max_output_tokens: 0 } } as Parameters<NonNullable<typeof hooks.beforeAttempt>>[0]; await hooks.beforeAttempt!(attempt); await hooks.onResult!({ ...attempt, status: 200, completedAt: Date.now(), streamed: false, terminalStream: true, response: Response.json({ usage: { input_tokens: 1, output_tokens: 0 } }) }); await accounting.savePricingVersion(workspace.id, { groupId: group, rates: rates(2), mode: "replace" });
  const originalTransaction = db.transaction.bind(db); let pause!: () => void, arrived!: () => void; const gate = new Promise<void>((resolve) => { pause = resolve; }), reached = new Promise<void>((resolve) => { arrived = resolve; }); let armed = true;
  (db as any).transaction = async (...args: any[]) => { const tx = await originalTransaction(...args); let claimed = false; return new Proxy(tx, { get(value, property) { if (property === "execute") return async (query: any) => { const result = await value.execute(query); if (query.sql?.startsWith("UPDATE pricing_jobs SET state='running'")) claimed = true; return result; }; if (property === "commit") return async () => { await value.commit(); if (armed && claimed) { armed = false; arrived(); await gate; } }; const member = Reflect.get(value, property); return typeof member === "function" ? member.bind(value) : member; } }); };
  const job = accounting.runPricingJobs(); await reached; let stopped = false; const shutdown = accounting.beginAccountingShutdown().then(() => { stopped = true; }); await Bun.sleep(25); expect(stopped).toBe(false); pause(); await Promise.all([job, shutdown]); (db as any).transaction = originalTransaction; db.close();
});
