export {};

Bun.env.NODE_ENV = "development"; Bun.env.APP_ORIGIN = ""; Bun.env.AUTH_DEFAULT_PASSWORD = "accounting-queue-crash"; Bun.env.DATABASE_URL = `file:/tmp/opencode/rawroute-accounting-crash-${crypto.randomUUID()}.db`; Bun.env.RAWROUTE_DATA_DIR = `/tmp/opencode/rawroute-accounting-crash-${crypto.randomUUID()}`;
const accounting = await import("./accounting"); const { db } = await import("./db"); const workspaces = await import("./workspaces"); const providers = await import("./providers"); const keys = await import("./gateway-keys");
const rates = { inputMicrosPerMillion: 1_000_000, outputMicrosPerMillion: 1_000_000, cacheReadMicrosPerMillion: 0, cacheCreationMicrosPerMillion: 0 };
await workspaces.ensureWorkspaceSchema(); await providers.ensureProviderSchema(); await keys.ensureGatewayKeySchema(); await accounting.ensureAccountingSchema();
const workspace = await workspaces.createWorkspace(`Crash ${crypto.randomUUID()}`); const key = await keys.createGatewayKey(workspace.id, "crash", crypto.randomUUID()); const provider = await providers.createProvider(workspace.id, { name: "Crash", prefix: `crash-${crypto.randomUUID().replaceAll("-", "").slice(0, 16)}`, baseUrl: "https://example.invalid", protocol: "openai-responses", authType: "none" }); const model = await providers.createProviderModel(workspace.id, provider.id, { name: "Crash", gatewaySuffix: "gpt-crash", upstreamModel: "gpt-crash" }); const group = await accounting.savePricingGroup(workspace.id, { name: "Crash", modelIds: [model.id] }); await accounting.savePricingVersion(workspace.id, { groupId: group, rates }); await accounting.saveBudget(workspace.id, { keyId: key.key.id, limitMicros: 1_000 });
const hooks = accounting.gatewayAccountingHooks(); const attempt = { attemptId: crypto.randomUUID(), requestId: crypto.randomUUID(), workspaceId: workspace.id, gatewayKeyId: key.key.id, requestedModel: model.gatewayModelId, model: { id: model.gatewayModelId, providerId: provider.id, providerPrefix: "crash", name: "Crash", upstreamModel: "gpt-crash", protocol: "openai-responses", source: "custom" }, providerId: provider.id, protocol: "openai-responses", startedAt: Date.now(), requestBodyBytes: 1, payload: { max_output_tokens: 0 } } as Parameters<NonNullable<typeof hooks.beforeAttempt>>[0]; await hooks.beforeAttempt!(attempt);
const originalTransaction = db.transaction.bind(db); (db as any).transaction = async (...args: any[]) => { const tx = await originalTransaction(...args); return new Proxy(tx, { get(value, property) { if (property === "execute") return async (query: any) => { if (query.sql?.startsWith("INSERT INTO accounting_settlement_queue")) throw new Error("injected queue handoff failure"); return value.execute(query); }; const member = Reflect.get(value, property); return typeof member === "function" ? member.bind(value) : member; } }); };
await hooks.onResult!({ ...attempt, status: 200, completedAt: Date.now(), streamed: false, terminalStream: true, response: Response.json({ usage: { input_tokens: 10, output_tokens: 0 } }) });
await Bun.write(Bun.env.ACCOUNTING_QUEUE_CRASH_STATE!, JSON.stringify({ databaseUrl: Bun.env.DATABASE_URL, workspaceId: workspace.id, attemptId: attempt.attemptId })); process.exit(0);
