import { expect, test } from "bun:test";

Bun.env.NODE_ENV = "development"; Bun.env.APP_ORIGIN = ""; Bun.env.AUTH_DEFAULT_PASSWORD = "accounting-native-drain"; Bun.env.DATABASE_URL = `file:/tmp/opencode/rawroute-accounting-native-${crypto.randomUUID()}.db`; Bun.env.RAWROUTE_DATA_DIR = `/tmp/opencode/rawroute-accounting-native-${crypto.randomUUID()}`;
const accounting = await import("./accounting"); const { db } = await import("./db"); const workspaces = await import("./workspaces"); const providers = await import("./providers"); const keys = await import("./gateway-keys"); const routing = await import("./routing"); const runtime = await import("./gateway-runtime"); const gateway = await import("./gateway-http");
const rates = { inputMicrosPerMillion: 1_000_000, outputMicrosPerMillion: 1_000_000, cacheReadMicrosPerMillion: 0, cacheCreationMicrosPerMillion: 0 };

test("gateway shutdown waits for the unmodified native source monitor", async () => {
  await workspaces.ensureWorkspaceSchema(); await providers.ensureProviderSchema(); await keys.ensureGatewayKeySchema(); await routing.ensureRoutingSchema(); await accounting.ensureAccountingSchema();
  const workspace = await workspaces.createWorkspace(`Native ${crypto.randomUUID()}`); const key = await keys.createGatewayKey(workspace.id, "native", crypto.randomUUID()); const provider = await providers.createProvider(workspace.id, { name: "Native", prefix: `native-${crypto.randomUUID().replaceAll("-", "").slice(0, 16)}`, baseUrl: "https://example.invalid", protocol: "openai-responses", authType: "none" }); const model = await providers.createProviderModel(workspace.id, provider.id, { name: "Native", gatewaySuffix: "gpt-native", upstreamModel: "gpt-native" }); const group = await accounting.savePricingGroup(workspace.id, { name: "Native", modelIds: [model.id] }); await accounting.savePricingVersion(workspace.id, { groupId: group, rates });
  const hooks = accounting.gatewayAccountingHooks(); let release!: () => void, reached!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }), arrived = new Promise<void>((resolve) => { reached = resolve; }); const originalTransaction = db.transaction.bind(db); let monitorStarted = false, armed = true, monitors = 0;
  (db as any).transaction = async (...args: any[]) => { if (monitorStarted && armed) { armed = false; reached(); await gate; } return await originalTransaction(...args); };
  const restore = runtime.setGatewayRuntimeDependenciesForTesting({ hooks: { ...hooks, onStream: async (attemptId: string, stream: ReadableStream<Uint8Array>) => { monitors++; monitorStarted = true; await hooks.onStream!(attemptId, stream); } }, fetch: (async () => new Response('data: {"type":"response.completed","response":{"usage":{"input_tokens":10,"output_tokens":0}}}\n\n', { headers: { "content-type": "text/event-stream" } })) as unknown as typeof fetch });
  const response = await gateway.gatewayRequest(new Request("http://gateway.test/v1/messages", { method: "POST", headers: { authorization: `Bearer ${key.secret}`, "content-type": "application/json" }, body: JSON.stringify({ model: model.gatewayModelId, messages: [{ role: "user", content: "hi" }], stream: true }) }) as any); await response.text(); await arrived;
  let stopped = false; const shutdown = Promise.all([gateway.beginGatewayShutdown(), accounting.beginAccountingShutdown()]).then(() => { stopped = true; }); await Bun.sleep(25); expect(stopped).toBe(false); expect(monitors).toBe(1); release(); await shutdown;
  const event = await db.execute({ sql: "SELECT status,cost_micros FROM usage_events WHERE workspace_id=?", args: [workspace.id] }); expect(event.rows[0]).toMatchObject({ status: 200, cost_micros: 10 }); restore(); (db as any).transaction = originalTransaction; db.close();
});
