import type { BunRequest } from "bun";
import { requireWorkspaceRequestScope, RequestScopeError, requestScopeErrorResponse } from "./request-scope";
import { CodexError, cancelCodexLogin, deleteCodexAccount, ensureCodexProvider, listCodexAccounts, listCodexCleanup, listCodexModels, pollCodexLogin, quotaForAccount, redeemCodexCredit, reorderCodexAccounts, retryCodexCleanup, setCodexModelEnabled, startCodexLogin, submitCodexCallback, updateCodexAccount } from "./codex";

async function body(request: Request): Promise<Record<string, unknown>> { try { const value = await request.json(); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; } catch { throw new CodexError("Request body must be valid JSON."); } }
async function scoped(request: BunRequest, mutate: boolean, action: (workspaceId: string) => Promise<Response>): Promise<Response> { try { const scope = await requireWorkspaceRequestScope(request, { mutate }); return await action(scope.workspace.id); } catch (error) { if (error instanceof RequestScopeError) return requestScopeErrorResponse(error); const item = error instanceof CodexError ? error : new CodexError("Codex service is temporarily unavailable.", 502); return Response.json({ error: item.message }, { status: item.status, headers: { "cache-control": "no-store" } }); } }
export function getCodex(request: BunRequest): Promise<Response> { return scoped(request, false, async (workspaceId) => { await ensureCodexProvider(workspaceId); return Response.json({ accounts: await listCodexAccounts(workspaceId), models: await listCodexModels(workspaceId), cleanup: await listCodexCleanup(workspaceId) }, { headers: { "cache-control": "no-store" } }); }); }
export function postCodexStart(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => Response.json(await startCodexLogin(workspaceId))); }
export function postCodexCallback(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { const input = await body(request); if (typeof input.loginId !== "string" || typeof input.redirectUrl !== "string") throw new CodexError("Login ID and callback URL are required."); await submitCodexCallback(workspaceId, input.loginId, input.redirectUrl); return Response.json({ ok: true }); }); }
export function postCodexPoll(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { const input = await body(request); if (typeof input.loginId !== "string") throw new CodexError("CLIProxy login ID is required."); const result = await pollCodexLogin(workspaceId, input.loginId, input.name); return Response.json(result, { status: result.status === "pending" ? 202 : 200 }); }); }
export function postCodexCancel(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { const input = await body(request); if (typeof input.loginId !== "string") throw new CodexError("CLIProxy login ID is required."); await cancelCodexLogin(workspaceId, input.loginId); return Response.json({ ok: true }); }); }
function accountId(request: BunRequest): string { return (request as BunRequest & { params: { accountId?: string } }).params?.accountId ?? ""; }
export function patchCodexAccount(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { await updateCodexAccount(workspaceId, accountId(request), await body(request)); return Response.json({ ok: true }); }); }
export function deleteCodexAccountHttp(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { await deleteCodexAccount(workspaceId, accountId(request)); return Response.json({ ok: true }); }); }
export function getCodexQuota(request: BunRequest): Promise<Response> { return scoped(request, false, async (workspaceId) => Response.json(await quotaForAccount(workspaceId, accountId(request)))); }
export function postCodexReset(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { await redeemCodexCredit(workspaceId, accountId(request), (await body(request)).confirmation); return Response.json({ ok: true }); }); }
export function patchCodexModel(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { const input = await body(request); const id = (request as BunRequest & { params: { modelId?: string } }).params?.modelId ?? ""; await setCodexModelEnabled(workspaceId, id, input.enabled); return Response.json({ ok: true }); }); }
export function postCodexCleanupRetry(request: BunRequest): Promise<Response> { return scoped(request, true, async () => { await retryCodexCleanup(); return Response.json({ ok: true }); }); }
export function postCodexReorder(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { await reorderCodexAccounts(workspaceId, (await body(request)).accountIds); return Response.json({ ok: true }); }); }
