import type { BunRequest } from "bun";
import { ModelShareError, listIncomingModelShares, listOutgoingModelShares, listShareTargets, setModelShareTargets } from "./model-shares";
import { RequestScopeError, requireWorkspaceRequestScope, runWithWorkspaceScope } from "./request-scope";
import { admitWorkspaceWrite } from "./workspaces";

function json(value: unknown, status = 200) { return Response.json(value, { status, headers: { "Cache-Control": "no-store" } }); }
function failure(error: unknown) { if (error instanceof ModelShareError || error instanceof RequestScopeError) return json({ error: error.message }, error.status); console.error("Model share request failed."); return json({ error: "Model sharing is temporarily unavailable." }, 503); }
async function scoped(request: BunRequest, mutate: boolean, action: (workspaceId: string) => Promise<Response>): Promise<Response> { try { const scope = await requireWorkspaceRequestScope(request, { mutate }); return await runWithWorkspaceScope(scope, () => action(scope.workspace.id)); } catch (error) { return failure(error); } }
async function read(request: BunRequest): Promise<Record<string, unknown>> { if (request.headers.get("content-type")?.split(";", 1)[0] !== "application/json") throw new ModelShareError("Content-Type must be application/json.", 415); const payload: unknown = await request.json().catch(() => undefined); if (!payload || typeof payload !== "object" || Array.isArray(payload) || Object.keys(payload).some((key) => key !== "modelId" && key !== "recipientWorkspaceIds")) throw new ModelShareError("Request body is invalid."); return payload as Record<string, unknown>; }

/** Owner-scoped CRUD; recipient lists are available only through their own scoped routing DTO. */
export function getModelShares(request: BunRequest): Promise<Response> { return scoped(request, false, async (workspaceId) => { const modelId = new URL(request.url).searchParams.get("modelId")?.trim(); if (!modelId) throw new ModelShareError("Model ID is required."); const [targets, shares] = await Promise.all([listShareTargets(workspaceId, modelId), listOutgoingModelShares(workspaceId, modelId)]); return json({ targets, shares }); }); }
export function getIncomingModelShares(request: BunRequest): Promise<Response> { return scoped(request, false, async (workspaceId) => json({ shares: await listIncomingModelShares(workspaceId) })); }
export function putModelShares(request: BunRequest): Promise<Response> { return scoped(request, true, async (workspaceId) => { const input = await read(request); if (typeof input.modelId !== "string" || !Array.isArray(input.recipientWorkspaceIds)) throw new ModelShareError("Model sharing request is invalid."); const admission = await admitWorkspaceWrite(workspaceId); if (!admission) throw new ModelShareError("Workspace is unavailable.", 409); try { return json({ shares: await setModelShareTargets(workspaceId, input.modelId, input.recipientWorkspaceIds) }); } finally { admission.release(); } }); }
