import type { BunRequest } from "bun";
import { createHash } from "node:crypto";
import { requireGlobalRequestScope, RequestScopeError, requestScopeErrorResponse } from "../request-scope";
import { CodexError, finishGlobalCodexLogin, isManagedCodexAuthFile, startGlobalCodexLogin } from "../codex";
import { cliproxyManagement, cliproxyManagementJson, withCliproxyManagementLock } from "./index";
import { runAdmittedCliproxyMutation } from "./http";
import { getDataRoot } from "./service";
import { getServicePaths, readSecret } from "./store";

const oauth = new Set(["anthropic", "codex", "antigravity", "kimi", "xai"]);
const settings: Record<string, string> = { debug: "debug", loggingToFile: "logging-to-file", usageStatisticsEnabled: "usage-statistics-enabled", requestRetry: "request-retry", maxRetryInterval: "max-retry-interval", routingStrategy: "routing/strategy" };
const routingStrategies = new Set(["round-robin", "fill-first"]);
function error(error: unknown): Response { if (error instanceof RequestScopeError) return requestScopeErrorResponse(error); if (error instanceof CodexError) return Response.json({ error: error.message }, { status: error.status, headers: { "cache-control": "no-store" } }); const status = typeof (error as { status?: unknown })?.status === "number" ? (error as { status: number }).status : 502; return Response.json({ error: error instanceof Error ? error.message : "CLIProxy management is unavailable." }, { status: status >= 400 && status <= 599 ? status : 502, headers: { "cache-control": "no-store" } }); }
async function global(request: BunRequest, mutate: boolean, action: () => Promise<Response>): Promise<Response> { try { await requireGlobalRequestScope(request, { mutate }); return await (mutate ? runAdmittedCliproxyMutation(() => withCliproxyManagementLock(action)) : action()); } catch (caught) { return error(caught); } }
function redactString(value: string): string {
  return value
    // JSON, quoted, escaped and plain `name=value` secret representations.
    // The value matcher intentionally accepts both JSON quotes and the literal
    // backslash-escaped quotes often embedded in a log line. It consumes up to
    // a structural delimiter, not merely a bearer-shaped token.
    .replace(/((?:\\?["'])?(?:(?:access|refresh|id)[_-]?token|api[_-]?key)(?:\\?["'])?\s*[:=]\s*)(?:\\?["'])?(?:\\.|[^\s,;}])+/gi, "$1[REDACTED]")
    .replace(/((?:x[-_]?api[-_]?key|api[-_]?key|authorization)\s*:\s*)(?:bearer\s+)?[^\s,;]+/gi, "$1[REDACTED]")
    .replace(/\b(?:bearer|basic)\s+[\w.~+/=-]+/gi, "[REDACTED]")
    // Includes conventional and percent-encoded query separators/keys.
    .replace(/(?:[?&]|%3[fF]|%26)(?:token|access(?:_|%5[fF])token|refresh(?:_|%5[fF])token|api(?:_|%5[fF]|-)key)=(?:[^&#\s]|%[0-9a-fA-F]{2})+/gi, "[REDACTED]");
}
function redact(value: unknown): unknown { if (typeof value === "string") return redactString(value); if (Array.isArray(value)) return value.map(redact); if (!value || typeof value !== "object") return value; const output: Record<string, unknown> = {}; for (const [key, item] of Object.entries(value as Record<string, unknown>)) if (!/(token|secret|password|authorization|api[_-]?key|refresh|id_token)/i.test(key)) output[key] = redact(item); return output; }
async function object(request: Request): Promise<Record<string, unknown>> { const value = await request.json().catch(() => undefined); if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Request body must be a JSON object."); return value as Record<string, unknown>; }
function apiKeyId(value: string) { return `key-${createHash("sha256").update(value).digest("hex").slice(0, 16)}`; }
function apiKeyMetadata(value: string, _index: number, managed: string) { return { id: apiKeyId(value), masked: `••••${value.slice(-4)}`, managedTransport: value === managed }; }
export function getCliproxyApiKeys(request: BunRequest): Promise<Response> { return global(request, false, async () => { const { response, data } = await cliproxyManagementJson<{ "api-keys"?: unknown[] }>("/v0/management/api-keys"); if (!response.ok) return Response.json({ error: "CLIProxy API key management is unavailable." }, { status: response.status }); const managed = readSecret(getServicePaths(getDataRoot()).apiKey); const keys = (data?.["api-keys"] || []).filter((key): key is string => typeof key === "string"); return Response.json({ apiKeys: keys.map((key, index) => apiKeyMetadata(key, index, managed)) }); }); }
export function putCliproxyApiKeys(request: BunRequest): Promise<Response> { return global(request, true, async () => { const input = await object(request); const add = typeof input.add === "string" ? input.add.trim() : ""; const replacement = Array.isArray(input.apiKeys) && input.apiKeys.every((item) => typeof item === "string" && item.trim()) ? input.apiKeys.map((key) => (key as string).trim()) : undefined; if (!add && !replacement) return Response.json({ error: "Provide an API key to add or a complete replacement list." }, { status: 400 }); const managed = readSecret(getServicePaths(getDataRoot()).apiKey); let keys = replacement; if (add) { const current = await cliproxyManagementJson<{ "api-keys"?: unknown[] }>("/v0/management/api-keys"); if (!current.response.ok) return Response.json({ error: "CLIProxy API key management is unavailable." }, { status: current.response.status }); keys = [...(current.data?.["api-keys"] || []).filter((key): key is string => typeof key === "string"), add]; } const safe = [...new Set([...(keys ?? []), managed])]; const response = await cliproxyManagement("/v0/management/api-keys", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(safe) }); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
export function deleteCliproxyApiKey(request: BunRequest): Promise<Response> { return global(request, true, async () => { const keyId = (request as BunRequest & { params?: { keyId?: string } }).params?.keyId ?? ""; const current = await cliproxyManagementJson<{ "api-keys"?: unknown[] }>("/v0/management/api-keys"); if (!current.response.ok) return Response.json({ error: "CLIProxy API key management is unavailable." }, { status: current.response.status }); const managed = readSecret(getServicePaths(getDataRoot()).apiKey); const keys = (current.data?.["api-keys"] || []).filter((key): key is string => typeof key === "string"); const target = keys.find((key) => apiKeyId(key) === keyId); if (!target) return Response.json({ error: "CLIProxy API key not found." }, { status: 404 }); if (target === managed) return Response.json({ error: "The RawRoute transport key cannot be revoked." }, { status: 409 }); const response = await cliproxyManagement("/v0/management/api-keys", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(keys.filter((key) => key !== target).concat(managed).filter((key, index, all) => all.indexOf(key) === index)) }); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
export function getCliproxyAuthFiles(request: BunRequest): Promise<Response> { return global(request, false, async () => { const { response, data } = await cliproxyManagementJson<{ files?: unknown[] }>("/v0/management/auth-files"); if (!response.ok) return Response.json({ error: "CLIProxy authentication status is unavailable." }, { status: response.status }); return Response.json({ files: redact(data?.files || []) }); }); }
async function unmanaged(name: unknown): Promise<string> { if (typeof name !== "string" || !name.trim() || name.length > 512 || /[\0\r\n]/.test(name)) throw new Error("Auth-file name is invalid."); const file = name.trim(); if (await isManagedCodexAuthFile(file)) throw new Error("Workspace-owned Codex auth files must be managed from that workspace."); return file; }
export function patchCliproxyAuthFile(request: BunRequest): Promise<Response> { return global(request, true, async () => { const input = await object(request); const name = await unmanaged(input.name); const response = await cliproxyManagement("/v0/management/auth-files/status", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, disabled: input.disabled === true }) }); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
export function deleteCliproxyAuthFile(request: BunRequest): Promise<Response> { return global(request, true, async () => { const name = await unmanaged(new URL(request.url).searchParams.get("name")); const response = await cliproxyManagement(`/v0/management/auth-files?name=${encodeURIComponent(name)}`, { method: "DELETE" }); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
export function getCliproxySettings(request: BunRequest): Promise<Response> { return global(request, false, async () => { const { response, data } = await cliproxyManagementJson<Record<string, unknown>>("/v0/management/config"); if (!response.ok) return Response.json({ error: "CLIProxy settings are unavailable." }, { status: response.status }); const config = redact(data) as Record<string, unknown>; const routing = config.routing && typeof config.routing === "object" ? config.routing as Record<string, unknown> : {}; return Response.json({ debug: config.debug, loggingToFile: config["logging-to-file"], usageStatisticsEnabled: config["usage-statistics-enabled"], requestRetry: config["request-retry"], maxRetryInterval: config["max-retry-interval"], routingStrategy: routing.strategy }); }); }
export function patchCliproxySettings(request: BunRequest): Promise<Response> { return global(request, true, async () => { const input = await object(request); if (input.routingStrategy !== undefined && (typeof input.routingStrategy !== "string" || !routingStrategies.has(input.routingStrategy))) return Response.json({ error: "Routing strategy must be round-robin or fill-first." }, { status: 400 }); for (const [name, value] of Object.entries(input)) { const endpoint = settings[name]; if (!endpoint) continue; const response = await cliproxyManagement(`/v0/management/${endpoint}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ value }) }); if (!response.ok) return Response.json({ error: `CLIProxy setting ${name} could not be updated.` }, { status: response.status }); } return Response.json({ ok: true }); }); }
export async function startCliproxyOauth(request: BunRequest): Promise<Response> { try { await requireGlobalRequestScope(request, { mutate: true }); const provider = (request as BunRequest & { params: { provider?: string } }).params?.provider ?? ""; if (!oauth.has(provider)) return Response.json({ error: "Unsupported CLIProxy login provider." }, { status: 400 }); const data = provider === "codex" ? await startGlobalCodexLogin() : await runAdmittedCliproxyMutation(() => withCliproxyManagementLock(async () => { const { response, data } = await cliproxyManagementJson<Record<string, unknown>>(`/v0/management/${provider}-auth-url`); if (!response.ok) throw new Error("CLIProxy login could not be started."); return data ?? {}; })); return Response.json(redact(data) as Record<string, unknown>); } catch (caught) { return error(caught); } }
export function cliproxyOauthStatus(request: BunRequest): Promise<Response> { return global(request, false, async () => { const state = new URL(request.url).searchParams.get("state"); if (!state) return Response.json({ error: "OAuth state is required." }, { status: 400 }); const { response, data } = await cliproxyManagementJson<{ status?: unknown }>(`/v0/management/get-auth-status?state=${encodeURIComponent(state)}`); const status = typeof data?.status === "string" ? data.status.toLowerCase() : "error"; if (response.ok && ["ok", "error", "failed", "cancelled", "canceled", "expired"].includes(status)) await finishGlobalCodexLogin(state); return Response.json(redact(data) || { status: "error" }, { status: response.status }); }); }
export function cancelCliproxyOauth(request: BunRequest): Promise<Response> { return global(request, true, async () => { const state = new URL(request.url).searchParams.get("state"); if (!state) return Response.json({ error: "OAuth state is required." }, { status: 400 }); const response = await cliproxyManagement(`/v0/management/oauth-session?state=${encodeURIComponent(state)}`, { method: "DELETE" }); if (response.ok) await finishGlobalCodexLogin(state); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
export function postCliproxyOauthCallback(request: BunRequest): Promise<Response> { return global(request, true, async () => { const provider = (request as BunRequest & { params: { provider?: string } }).params?.provider ?? ""; if (!oauth.has(provider)) return Response.json({ error: "Unsupported CLIProxy login provider." }, { status: 400 }); const input = await object(request); const response = await cliproxyManagement("/v0/management/oauth-callback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider, ...input }) }); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
/** Public OAuth landing callback: provider state/code is forwarded privately and never logged or persisted here. */
export async function publicCliproxyOauthCallback(request: BunRequest): Promise<Response> { const provider = (request as BunRequest & { params: { provider?: string } }).params?.provider ?? ""; if (!oauth.has(provider)) return new Response("Not found", { status: 404 }); const url = new URL(request.url); const state = url.searchParams.get("state") ?? ""; const code = url.searchParams.get("code") ?? ""; const oauthError = url.searchParams.get("error") ?? url.searchParams.get("error_description") ?? ""; if (!state || (!code && !oauthError)) return new Response("Invalid OAuth callback", { status: 400 }); let failureStatus = 502; const response = await runAdmittedCliproxyMutation(() => withCliproxyManagementLock(async () => { const completed = await cliproxyManagement("/v0/management/oauth-callback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ provider, state, ...(code ? { code } : { error: oauthError }) }) }); return completed; })).catch((error: unknown) => { const status = (error as { status?: unknown })?.status; if (typeof status === "number" && status >= 400 && status <= 599) failureStatus = status; return undefined; }); return new Response(response?.ok ? "Authorization received. You can return to RawRoute." : "Authorization could not be completed.", { status: response?.ok ? 200 : failureStatus, headers: { "content-type": "text/plain; charset=utf-8", "cache-control": "no-store" } }); }
export function getCliproxyLogs(request: BunRequest): Promise<Response> { return global(request, false, async () => { const { response, data } = await cliproxyManagementJson("/v0/management/logs"); return Response.json(redact(data) || {}, { status: response.status }); }); }
export function deleteCliproxyLogs(request: BunRequest): Promise<Response> { return global(request, true, async () => { const response = await cliproxyManagement("/v0/management/logs", { method: "DELETE" }); return Response.json({ ok: response.ok }, { status: response.ok ? 200 : response.status }); }); }
